-- CreateTable
CREATE TABLE "lead_data" (
    "zoominfo_contact_id" BIGINT NOT NULL,
    "last_name" VARCHAR(100),
    "first_name" VARCHAR(100),
    "middle_name" VARCHAR(100),
    "salutation" VARCHAR(50),
    "suffix" VARCHAR(50),
    "job_title" VARCHAR(200),
    "management_level" VARCHAR(100),
    "job_function" VARCHAR(150),
    "department" VARCHAR(150),
    "direct_phone_number" VARCHAR(50),
    "email_address" VARCHAR(150),
    "mobile_phone" VARCHAR(50),
    "zoominfo_contact_profile_url" VARCHAR(300),
    "linkedin_contact_profile_url" VARCHAR(300),
    "person_street" VARCHAR(200),
    "person_city" VARCHAR(100),
    "person_state" VARCHAR(100),
    "person_zip_code" VARCHAR(20),
    "country" VARCHAR(100),
    "zoominfo_company_id" BIGINT,
    "company_name" VARCHAR(200),
    "website" VARCHAR(200),
    "founded_year" INTEGER,
    "primary_industry" VARCHAR(150),
    "primary_sub_industry" VARCHAR(150),
    "all_industries" TEXT,
    "all_sub_industries" TEXT,
    "industry_hierarchical_category" VARCHAR(200),
    "secondary_industry_hierarchical_category" VARCHAR(200),
    "zoominfo_company_profile_url" VARCHAR(300),
    "linkedin_company_profile_url" VARCHAR(300),
    "facebook_company_profile_url" VARCHAR(300),
    "twitter_company_profile_url" VARCHAR(300),
    "ownership_type" VARCHAR(100),
    "business_model" VARCHAR(100),
    "certified_active_company" BOOLEAN DEFAULT false,
    "full_address" VARCHAR(300),
    "status" VARCHAR(50) DEFAULT 'new',
    "last_email_sent_at" TIMESTAMP(3),
    "last_replied_at" TIMESTAMP(3),
    "follow_up_count" INTEGER DEFAULT 0,
    "thread_id" VARCHAR(200),
    "next_follow_up_at" TIMESTAMP(3),
    "meeting_scheduled_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "lead_data_pkey" PRIMARY KEY ("zoominfo_contact_id")
);
